PullBranch
EvilBorsch/Task2_proga_multi pull request #1
Opened 2019-10-20 19:39 UTC by EvilBorsch

Added all

2019-10-20 19:51 UTC, EvilBorsch commented
Пока что добавил статическую библиотеку без потоков и наметил как буду делать тесты, внутри динамической библиотеке сделаю распараллеливание, один поток будет считать сумму элементов на диагонале сверху вниз до середины, а второй снизу вверх до середины

2019-10-21 06:36 UTC, leshiy1295 commented
Ревью будет проводиться только строго после выполнения всей задачи целиком

2019-10-21 19:29 UTC, EvilBorsch commented
Выполнил всю задачу!

2019-10-22 09:26 UTC, leshiy1295 requested changes

2019-10-22 09:26 UTC, leshiy1295 commented on .travis.yml
> +    - ar r libstatic.a *.o
почему одни и те же файлы добавляются как в статическую, так и динамическую библиотеку?
нужно одну реализацию оформить в виде статической, а вторую - в виде динамической
а из main/тестов использовать либо ту, либо ту

2019-10-22 09:26 UTC, leshiy1295 commented on .travis.yml
> +    - gcc -o zadanie_2_multithread_proga *.o -L. -ldynamic -lstatic -lpthread -Wl,-rpath,.
почему не используется make/CMake?

2019-10-22 09:26 UTC, leshiy1295 commented on cmake-build-debug/CMakeCache.txt
> +# This is the CMakeCache file.
этот файл лишний

2019-10-22 09:26 UTC, leshiy1295 commented on cmake-build-debug/CMakeFiles/3.15.3/CMakeCCompiler.cmake
> +set(CMAKE_C_COMPILER "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc")
вообще папки cmake-build-debug быть в репозитории не должно

2019-10-22 09:26 UTC, leshiy1295 commented on libdynamic.h
> +#endif //ZADANIE_2_MULTITHREAD_PROGA_LIBDYNAMIC_H
смысл этого endif, если все функции идут после?

2019-10-22 09:26 UTC, leshiy1295 commented on libdynamic.h
> +void *threadFunc(void *thread_data);
в C используется sneak_case
+ название функции непонятное

2019-10-22 09:26 UTC, leshiy1295 commented on libdynamic.h
> +long int find_sigma_diagonals(char **matrix1, int N);
должны быть понятные названия переменных

2019-10-22 09:26 UTC, leshiy1295 commented on libdynamic.so.dSYM/Contents/Info.plist
> +<?xml version="1.0" encoding="UTF-8"?>
этого файла быть в репозитории не должно

2019-10-22 09:26 UTC, leshiy1295 commented on libdynamic.so.dSYM/Contents/Info.plist
> +<?xml version="1.0" encoding="UTF-8"?>
как и бинарника .so

2019-10-22 09:26 UTC, leshiy1295 commented on libstatic.h
> +#endif //ZADANIE_2_MULTITHREAD_PROGA_MAIN_H
снова ошибка с макросами...

2019-10-22 09:26 UTC, leshiy1295 commented on libstatic.h
> +void print_mat(char **mat, size_t n);
как минимум тут не хватает const

2019-10-22 09:26 UTC, leshiy1295 commented on main.c
> +        char **mat = init_with_num(n, 2);
магические константы
+ assert работает только в DEBUG-режиме...

2019-10-22 09:26 UTC, leshiy1295 commented on .travis.yml
> +    - ./zadanie_2_multithread_proga
не посчитано покрытие кода тестами

2019-10-22 09:26 UTC, leshiy1295 commented on main.c
> +        int n = 3;
лучше разбить на функции с понятным описанием того, что в тесте проверяется

2019-10-22 09:26 UTC, leshiy1295 commented on main.c
> +        assert(get_sigma_diagonal(mat, n) == find_sigma_diagonals(mat, n));
get_sigma и find_sigma - ну видно же, что названия плохие

2019-10-22 09:26 UTC, leshiy1295 commented on source/libdynamic.c
> +#include "../libdynamic.h"
сразу видно, что не используется (или неправильно используется) CMake
относительных путей быть не должно

2019-10-22 09:26 UTC, leshiy1295 commented on source/libdynamic.c
> +#include <assert.h>
список include-ов должен быть в алфавитном порядке

2019-10-22 09:26 UTC, leshiy1295 commented on source/libdynamic.c
> +    pthrData *data = (pthrData *) thread_data;
что если thread_data == NULL?

2019-10-22 09:26 UTC, leshiy1295 commented on source/libdynamic.c
> +    if (N < 4 && N > 1) NUM_THREADS = 2;
магические константы
точное количество потоков/процессов нужно определять в зависимости от окружения среды
если доступно только 1 ядро, то использование нескольких потоков не оправдано

2019-10-22 09:26 UTC, leshiy1295 commented on source/libdynamic.c
> +    if (N == 1) return matrix1[0][0];
не нужно экономить на переводах строк и {}...

2019-10-22 09:26 UTC, leshiy1295 commented on source/libdynamic.c
> +    int NUM_THREADS = 4;
что если matrix1 == NULL? или N < 0?

почему обычная переменная названа через CAPS_LOCK? если это default, то нужно вынести с соответствующим названием и пометить const

2019-10-22 09:26 UTC, leshiy1295 commented on source/libdynamic.c
> +    pthread_t *threads = (pthread_t *) malloc(NUM_THREADS * sizeof(pthread_t));
assert-ы - это подсказка во время debug
во время release-сборки они игнорируются - программа просто упадёт без какой-либо информации
этого допускать нельзя. Нужно корректно все такие падения обрабатывать

2019-10-22 09:26 UTC, leshiy1295 commented on source/libdynamic.c
> +    for (int i = 0; i < NUM_THREADS; i++) pthread_cancel(threads[i]);
зачем cancel после join?

2019-10-22 09:26 UTC, leshiy1295 commented on source/libdynamic.c
> +    long int temp = result + matrix1[0][0];
непонятное название переменной...
и вообще их назначение

2019-10-22 09:26 UTC, leshiy1295 commented on source/libdynamic.c
> +        threadData[i].start_str = prev_start;
start_str... prev_start..
по коду вообще непонятно, что делает программа

2019-10-22 09:26 UTC, leshiy1295 commented on source/libdynamic.c
> +    for (int i = data->start_str; i < data->start_str + data->num_of_strs; i++) {
что если k < 0?

2019-10-22 09:26 UTC, leshiy1295 commented on source/libdynamic.c
> +        k++;
предпочитайте ++k вместо ++k

2019-10-22 09:26 UTC, leshiy1295 commented on source/libstatic.c
> +#include "../libstatic.h"
относительный include

2019-10-22 09:26 UTC, leshiy1295 commented on source/libstatic.c
> +        assert(mat[i] != NULL);
если просто падать, то вся прежде выделенная память освобождена не будет
нужно корректно всё это обрабатывать. Текущее решение - халтура

2019-10-22 09:26 UTC, leshiy1295 commented on source/libstatic.c
> +            scanf("%d", &chis);
результат scanf нужно проверять

2019-10-22 09:26 UTC, leshiy1295 commented on source/libstatic.c
> +            mat[i][j] = (char) chis;
почему сразу не вводить char?

2019-10-22 09:26 UTC, leshiy1295 commented on source/libstatic.c
> +char **init_with_num(size_t n, int num) {
почему передаётся int, если он трансформируется в char???

2019-10-22 09:26 UTC, leshiy1295 commented on source/libstatic.c
> +    if (n == 0) n = 3; //Для тестов
непонятно

2019-10-22 09:26 UTC, leshiy1295 commented on zadanie_2_multithread_proga.dSYM/Contents/Info.plist
> +<?xml version="1.0" encoding="UTF-8"?>
этого файла тоже быть не должно

2019-10-22 09:26 UTC, leshiy1295 commented on CMakeLists.txt
> +add_executable(zadanie_2_multithread_proga source/libstatic.c libstatic.h main.c source/libdynamic.c libdynamic.h)
нужно оформить как минимум два таргета - для основной программы и тестирующей
в зависимости от флагов при сборке в main должна использоваться либо одна, либо другая реализация
тестирующая программа должна использовать обе и сравнивать результаты их работы между собой и с правильным ответом

+ в таком виде от CMake никакого толку нет

2019-10-22 09:26 UTC, leshiy1295 commented on source/libstatic.c
> +char **init_matrix_from_keyboard(size_t n) {
стоило сделать универсальную функцию, которая может работать с произвольным входным потоком (stdin - это один из вариантов)

2019-10-22 09:26 UTC, leshiy1295 commented on source/libdynamic.c
> +    threadData[NUM_THREADS - 1].rowSize = NUM_THREADS;
почему сразу не инициализировать структуру целиком?

2019-10-22 09:26 UTC, leshiy1295 commented on main.c
> +    test();
main должен предоставлять возможность ввода
то, что сейчас - это не требуемая программа, а лишь тесты к ней

2019-10-22 09:26 UTC, leshiy1295 commented on main.c
> +void test() {
сначала нужно располагать интерфейс, а потом после main - реализацию...

2019-10-22 09:26 UTC, leshiy1295 commented on main.c
> +#include <stdio.h>
не приведено условие задачи

2019-10-22 09:26 UTC, leshiy1295 commented on .travis.yml
> +    - gcc -std=c11 -c -fPIC source/*.c
нужно собирать с -Wall -Werror -Wpedantic

2019-10-22 09:29 UTC, leshiy1295 commented
также нету cpplint и scan-build

2019-10-22 21:21 UTC, EvilBorsch commented
Пофикшено!

2019-10-23 20:35 UTC, EvilBorsch commented
Теперь еще code coverage есть

2019-10-24 10:19 UTC, leshiy1295 requested changes
в условии сказано, что нужно использовать процессы, а не потоки
таким образом, задача не реализована!

2019-10-24 10:19 UTC, leshiy1295 commented on .travis.yml
> +    - gcov *.c
высматривать значения процентов в логах CI неудобно
нужно генерировать html-отчёт и давать ссылку на него в Pull Request

2019-10-24 10:19 UTC, leshiy1295 commented on .travis.yml
> +    - gcc -std=c11 -c ./libstatic.c
нужно собирать программу с флагами -Wall -Werror -Wpedantic

2019-10-24 10:19 UTC, leshiy1295 commented on libdynamic.c
> +#define MEMORY_ERROR 28;
магическая константа

2019-10-24 10:19 UTC, leshiy1295 commented on libdynamic.c
> +static int16_t result = 0;
почему не использовать просто int?

2019-10-24 10:19 UTC, leshiy1295 commented on libdynamic.c
> +  char **matrix;
насколько эффективно выровнена структура?

2019-10-24 10:19 UTC, leshiy1295 commented on libdynamic.c
> +    perror("Memmory error");
внутренняя функция не должна ничего выводить наружу
выводить может только функция, взаимодействующая с пользователем

2019-10-24 10:19 UTC, leshiy1295 commented on libdynamic.c
> +  if (k < 0) k = 0;
не экономьте на {} и переносах строк

2019-10-24 10:19 UTC, leshiy1295 commented on libdynamic.c
> +    num_threads = 2;
почему?
откуда это взялось?
точное количество должно определяться из системных возможностей (количества ядер, например)

2019-10-24 10:19 UTC, leshiy1295 commented on libdynamic.c
> +    free(threads);
threads == NULL
зачем вызывается free?

2019-10-24 10:19 UTC, leshiy1295 commented on libdynamic.c
> +  threadData[num_threads - 1].rowSize = num_threads;
лучше переделать на инициализацию структур, а не полей

2019-10-24 10:19 UTC, leshiy1295 commented on libdynamic.c
> +    free(threadData);
threadData и так NULL
а вот threads тут уже не NULL...

2019-10-24 10:19 UTC, leshiy1295 commented on libstatic.c
> +// Copyright 2019 EvilBorsch
.so-файлы и другие бинарники класть в репозиторий не нужно

2019-10-24 10:19 UTC, leshiy1295 commented on libstatic.c
> +      if (chis < 0 || chis > 3) {
магические константы

2019-10-24 10:19 UTC, leshiy1295 commented on libstatic.c
> +    assert(mat[i] != NULL);
assert работает только в DEBUG-режиме...
нужно корректно обрабатывать этот случай в RELEASE

2019-10-24 10:19 UTC, leshiy1295 commented on libstatic.c
> +      free(mat[i]);
та же ошибка... совершенно непонятно, что тут освобождается, однако при этом то, что нужно - не освобождается

2019-10-24 10:19 UTC, leshiy1295 commented on libstatic.c
> +      printf("%d ", (mat[i][j]));
что если mat == NULL?

2019-10-24 10:19 UTC, leshiy1295 commented on libstatic.h
> +char **init_matrix_from_keyboard(size_t n);
from_keyboard - не поправлено
должен быть обобщённый ввод
+ нет уверенности в том, что ввод данных должен быть в библиотеке...

2019-10-24 10:19 UTC, leshiy1295 commented on libstatic.h
> +void del_mat(char **mat, size_t n);
интерфейс для обеих библиотек должен быть одинаковым

2019-10-24 10:19 UTC, leshiy1295 commented on libstatic.h
> +void print_mat(const char **mat, size_t n);
указатели менять можно?

2019-10-24 10:19 UTC, leshiy1295 commented on main.c
> +  int size;
комментариев с нерабочим кодом быть не должно

2019-10-24 10:19 UTC, leshiy1295 commented on main.c
> +    char **mat = init_with_num(n, 2);
действительно ли хранение полной матрицы эффективно с учётом условий задачи?
ведь половина памяти использоваться не будет

2019-10-24 10:19 UTC, leshiy1295 commented on main.c
> +    assert(get_sigma_diagonal(mat, n) == 3);
== n?

2019-10-24 10:19 UTC, leshiy1295 commented on main.c
> +    assert(find_sigma_diagonals(mat, n) > 1);
почему > 1?

2019-10-24 10:19 UTC, leshiy1295 commented on libdynamic.c
> +    pthread_create(&(threads[i]), NULL, summ_last_elements, &threadData[i]);
в условии сказано, что нужно использовать процессы, а не потоки
таким образом, задача не реализована!

2019-10-24 21:19 UTC, EvilBorsch commented on main.c
> +    char **mat = init_with_num(n, 2);
У меня не хранится полная матрица, а содержится только ее половинка(используемая)

2019-10-24 21:19 UTC, EvilBorsch commented
Переделал

2019-11-03 14:37 UTC, leshiy1295 requested changes

2019-11-03 14:37 UTC, leshiy1295 commented on .travis.yml
> +dist:     trusty
сейчас запускается два CI-билда на каждый пу

2019-11-03 14:37 UTC, leshiy1295 commented on .travis.yml
> +dist:     trusty
в сборке есть ворнинги => не передаётся ключ -Werror

2019-11-03 14:37 UTC, leshiy1295 commented on .travis.yml
> +dist:     trusty
нет html-отчёта на покрытие кода
+ нет иконок в Pull Request, ведущих на отчёты разных этапов CI

2019-11-03 14:37 UTC, leshiy1295 commented on .travis.yml
> +dist:     trusty
valgrind сейчас падает, но сборка проходит

2019-11-03 14:37 UTC, leshiy1295 commented on libdynamic.c
> +  if (started_str == (chisyad - 1) * kolvostrok) kolvostrok = N - started_str;
не нужно экономить на {}

2019-11-03 14:37 UTC, leshiy1295 commented on libdynamic.c
> +int process_summ_last_matrix_elements(int started_str, char **matrix, int N,
нигде не нужен const?

2019-11-03 14:37 UTC, leshiy1295 commented on libdynamic.c
> +#include <unistd.h>
алфавитный порядок

2019-11-03 14:37 UTC, leshiy1295 commented on libdynamic.c
> +int process_summ_last_matrix_elements(int started_str, char **matrix, int N,
N - может, лучше использовать size_t?
и что вообще такое N - непонятно из названия

2019-11-03 14:37 UTC, leshiy1295 commented on libdynamic.c
> +  int okonch_result = 0;
использовать транслит в названиях переменных - плохая практика

2019-11-03 14:37 UTC, leshiy1295 commented on libdynamic.c
> +    write(fd[1], buff,
нужно проверять результат работы функций

2019-11-03 14:37 UTC, leshiy1295 commented on libdynamic.c
> +    // подсчет элементов на диагонале для данного процесса
комментарии не нужны, если переменные называются понятно, и используются понятные названия функций

2019-11-03 14:37 UTC, leshiy1295 commented on libdynamic.c
> +      perror("Process Eroor");
функция обработки не должна ничего печатать при ошибке

2019-11-03 14:37 UTC, leshiy1295 commented on libdynamic.c
> +      read(fd[0], data, sizeof(data) + 1);  // Берем строку с которой считаем
что если произошла ошибка во время чтения?

2019-11-03 14:37 UTC, leshiy1295 commented on libdynamic.c
> +    int fd[2];
сколько открытых файловых дескрипторов вообще будет?
правильно ли осуществлено открытие/закрытие?

2019-11-03 14:37 UTC, leshiy1295 commented on libdynamic.c
> +    // printf("Received %d\n", buf[0]);
комментариев с нерабочим кодом быть не должно

2019-11-03 14:37 UTC, leshiy1295 commented on libdynamic.c
> +      exit(0);
стоит выносить логику работу отдельных процессов в функцию

2019-11-03 14:37 UTC, leshiy1295 commented on libdynamic.c
> +    waitpid(pid, &status, 0);
нужно обрабатывать результат работы всех функций

2019-11-03 14:37 UTC, leshiy1295 commented on libdynamic.h
> +#include <stdio.h>
ifndef/endif?

2019-11-03 14:37 UTC, leshiy1295 commented on libstatic.c
> +#define MEMMORY_ERROR 28
магическая константа

2019-11-03 14:37 UTC, leshiy1295 commented on libstatic.h
> +#include <stdio.h>
интерфейс у обеих библиотек должен быть абсолютно одинаковым, то есть всё должно работать с единым header-файлом
выбор той или иной реализации должен осуществляться на этапе линковки

2019-11-03 14:37 UTC, leshiy1295 commented on main.c
> +#define MAX_NUMBER 3
что это за магические константы?

2019-11-03 14:37 UTC, leshiy1295 commented on main.c
> +  test();
main должен предоставлять возможность пользовательского ввода

2019-11-03 14:37 UTC, leshiy1295 commented on main.c
> +    char **mat = init_with_num(n, 2);
то, что у Вас хранится - это не матрица, а вектор векторов...

2019-11-03 14:37 UTC, leshiy1295 commented on main.c
> +        assert(2 == (mat[i][j]));
ассерты работают только в DEBUG-режиме
в RELEASE-сборке они игнорируются

2019-11-03 14:37 UTC, leshiy1295 commented on main.c
> +    assert(get_sigma_diagonal(mat, n) == summa_diagonali(4, mat, n));
поскольку интерфейс должен быть общим, название основной функции должно быть одинаковым => должны быть отдельные тесты для обеих библиотек, а также стресс-тесты, и которые запускают обе программы на одинаковых входных данных и сравнивают результаты их работы между собой

2019-11-03 14:37 UTC, leshiy1295 commented on main.c
> +char **init_matrix_from_keyboard(const size_t n) {
где сейчас используется эта функция?

2019-11-03 14:37 UTC, leshiy1295 commented on main.c
> +      free(mat);
а что с первыми i выделенными mat[i]?

2019-11-03 14:56 UTC, leshiy1295 requested changes

2019-11-03 14:56 UTC, leshiy1295 commented on libdynamic.c
> +  int* pid = malloc((core_count + 1) * sizeof(int));
matrix может быть NULL

malloc может вернуть ошибку

2019-11-03 14:56 UTC, leshiy1295 commented on libdynamic.c
> +      exit(EAGAIN);
exit внутри цикла - моветон

2019-11-03 14:56 UTC, leshiy1295 commented on libdynamic.c
> +      write(fd[1], ans, sizeof(int));
результаты всех системных вызовов нужно проверять

2019-11-03 14:56 UTC, leshiy1295 commented on libstatic.c
> +    perror("Mat is null");
внутренняя функция ничего не должна выводить в общий stdout/stderr

2019-11-03 14:56 UTC, leshiy1295 commented on main.c
> +#include "libdynamic.h"
header-файл должен быть единым для обеих библиотек
конкретная реализация должна определяться на этапе сборки

2019-11-03 14:56 UTC, leshiy1295 commented on main.c
> +    assert(get_sigma_diagonal(mat, n) == n);
что если mat == NULL?

2020-01-23 15:14 UTC, merged